spring.application.name=portfolio-api
spring.jpa.hibernate.ddl-auto=update

spring.config.import=optional:configtree:/run/secrets/

spring.datasource.url=${db_url}
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
